apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-svc
spec:
  selector:
    matchLabels:
      app: order-svc
  template:
    metadata:
      labels:
        app: order-svc
    spec:
      containers:
      - name: order-container
        image: ordersvc
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        # env:
        #   - name: API_HOST
        #     valueFrom:
        #       configMapKeyRef:
        #         name: order-config
        #         key: apiHost
        #   - name: API_PORT
        #     valueFrom:
        #       configMapKeyRef:
        #         name: order-config
        #         key: apiPort
